version: "3"
services:
  webapp:
    build: .
    image: docker-flask-gpu
    ports:
      - "8000:8000"
    links:
      - redis
    deploy:
      replicas: 10
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  redis:
    image: redis
